# Generated by Django 5.0.3 on 2024-03-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
